<h1>Gibbs Sampling</h1>

In [3]:
import numpy as np

x = np.diag(np.full(10, 1))
print(x)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [53]:
# single iteration
x_ij = np.random.choice(10, size=(2,))
i, j = x_ij[0], x_ij[1]
print(i,j, x[i][j])

3 4 0


In [91]:
from math import exp
BETA = 1

i, j = 4, 3
print(x[i][j])

s_1, s_0 = 0, 0
(s_1, s_0) = (s_1, s_0) if i == 0 else (s_1 + (x[i-1][j] == 1), s_0 + (x[i-1][j] == 0))
(s_1, s_0) = (s_1, s_0) if i == 9 else (s_1 + (x[i+1][j] == 1), s_0 + (x[i+1][j] == 0))
(s_1, s_0) = (s_1, s_0) if j == 0 else (s_1 + (x[i][j-1] == 1), s_0 + (x[i][j-1] == 0))
(s_1, s_0) = (s_1, s_0) if j == 9 else (s_1 + (x[i][j+1] == 1), s_0 + (x[i][j+1] == 0))
print(s_1, s_0)

e_s_1 = exp(BETA * s_1)
e_s_0 = exp(BETA * s_0)

p_1 = e_s_1 / (e_s_1 + e_s_0)
print(p_1)

new_x_ij = np.random.choice([0,1], p=[1-p_1, p_1])
print(new_x_ij)

0
2 2
0.5
1


In [1]:
import numpy as np
from math import exp

x = np.diag(np.full(10, 1))
print(x)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [80]:
x = np.random.choice([0,1], size=(10,10), p = [0.5, 0.5])
print(x)

[[0 1 0 0 1 1 1 1 1 0]
 [0 0 1 0 1 0 1 1 1 0]
 [1 0 1 0 1 0 0 0 1 0]
 [0 0 1 1 0 0 1 0 0 0]
 [0 1 1 1 1 1 0 1 1 0]
 [1 1 1 1 0 1 0 0 1 0]
 [0 0 1 1 0 0 1 0 0 1]
 [1 0 1 1 1 0 0 0 1 0]
 [1 0 1 0 1 0 1 1 1 0]
 [1 0 0 0 0 1 0 0 0 1]]


In [103]:
x = [[0,1,0,0,1,1,1,1,1,0],
 [0,0,1,0,1,0,1,1,1,0],
 [1,0,1,0,1,0,0,0,1,0],
 [0,0,1,1,0,0,1,0,0,0],
 [0,1,1,1,1,1,0,1,1,0],
 [1,1,1,1,0,1,0,0,1,0],
 [0,0,1,1,0,0,1,0,0,1],
 [1,0,1,1,1,0,0,0,1,0],
 [1,0,1,0,1,0,1,1,1,1],
 [1,0,0,0,0,1,0,0,0,1]]

In [124]:
x = [[1, 0, 1, 0, 1, 0, 1, 0, 1, 0], 
     [0, 1, 0, 1, 0, 1, 0, 1, 0, 1], 
     [1, 0, 1, 0, 1, 0, 1, 0, 1, 0], 
     [0, 1, 0, 1, 0, 1, 0, 1, 0, 1], 
     [1, 0, 1, 0, 1, 0, 1, 0, 1, 0], 
     [0, 1, 0, 1, 0, 1, 0, 1, 0, 1], 
     [1, 0, 1, 0, 1, 0, 1, 0, 1, 0], 
     [0, 1, 0, 1, 0, 1, 0, 1, 0, 1], 
     [1, 0, 1, 0, 1, 0, 1, 0, 1, 0], 
     [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]]

In [154]:
BETA = 4
num_iter = 100
results = []

for _ in range(num_iter):
    x_ij = np.random.choice([i for i in range(10)], size=(2,))
    i, j = x_ij[0], x_ij[1]
    # if (j == 9) and ((i == 0) or (i == 9)):
    #     do_print = True
    print(f"x[{i}][{j}] = {x[i][j]}")
    
    s_1, s_0 = 0, 0
    (s_1, s_0) = (s_1, s_0) if i == 0 else (s_1 + (x[i-1][j] == 1), s_0 + (x[i-1][j] == 0))
    (s_1, s_0) = (s_1, s_0) if i == 9 else (s_1 + (x[i+1][j] == 1), s_0 + (x[i+1][j] == 0))
    (s_1, s_0) = (s_1, s_0) if j == 0 else (s_1 + (x[i][j-1] == 1), s_0 + (x[i][j-1] == 0))
    (s_1, s_0) = (s_1, s_0) if j == 9 else (s_1 + (x[i][j+1] == 1), s_0 + (x[i][j+1] == 0))
    # if i == 0:
    #     print
    # if do_print:
    print(s_1, s_0)
    
    e_s_1 = exp(BETA * s_1)
    e_s_0 = exp(BETA * s_0)
    
    p_1 = e_s_1 / (e_s_1 + e_s_0)
    # if do_print:
    print("p(x = 1) =", p_1)
    
    new_x_ij = np.random.choice([0,1], p=[1-p_1, p_1])
    # if do_print:
    print(f"x[{i}][{j}]: {x[i][j]} => {new_x_ij}")

    x[i][j] = new_x_ij
    results.append(x.copy())
    do_print = False

x[2][9] = 0
2 1
p(x = 1) = 0.9820137900379085
x[2][9]: 0 => 1
x[3][0] = 0
0 3
p(x = 1) = 6.144174602214718e-06
x[3][0]: 0 => 0
x[9][9] = 0
1 1
p(x = 1) = 0.5
x[9][9]: 0 => 0
x[3][8] = 0
4 0
p(x = 1) = 0.9999998874648379
x[3][8]: 0 => 1
x[8][5] = 1
4 0
p(x = 1) = 0.9999998874648379
x[8][5]: 1 => 1
x[3][4] = 0
3 1
p(x = 1) = 0.9996646498695334
x[3][4]: 0 => 1
x[5][2] = 1
2 2
p(x = 1) = 0.5
x[5][2]: 1 => 1
x[7][5] = 1
3 1
p(x = 1) = 0.9996646498695334
x[7][5]: 1 => 1
x[5][7] = 1
3 1
p(x = 1) = 0.9996646498695334
x[5][7]: 1 => 1
x[5][7] = 1
3 1
p(x = 1) = 0.9996646498695334
x[5][7]: 1 => 1
x[6][6] = 0
2 2
p(x = 1) = 0.5
x[6][6]: 0 => 0
x[7][1] = 1
2 2
p(x = 1) = 0.5
x[7][1]: 1 => 1
x[8][6] = 1
4 0
p(x = 1) = 0.9999998874648379
x[8][6]: 1 => 1
x[7][5] = 1
3 1
p(x = 1) = 0.9996646498695334
x[7][5]: 1 => 1
x[3][7] = 1
3 1
p(x = 1) = 0.9996646498695334
x[3][7]: 1 => 1
x[9][2] = 0
1 2
p(x = 1) = 0.01798620996209156
x[9][2]: 0 => 0
x[3][9] = 1
3 0
p(x = 1) = 0.9999938558253978
x[3][9]: 1 => 1
x[

In [156]:
# marginalize
prob_table = np.zeros((2,2))

for r in results:
    prob_table[r[0][9]][r[9][9]] += 1
print(prob_table)
print(prob_table / np.sum(prob_table))

[[  0. 100.]
 [  0.   0.]]
[[0. 1.]
 [0. 0.]]


In [158]:
print(x)

[[0, 1, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 1, 0, 0, 0, 0], [0, 0, 1, 1, 1, 1, 0, 0, 1, 1], [0, 0, 0, 0, 1, 1, 0, 1, 1, 1], [0, 0, 0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 1, 1, 1], [0, 1, 1, 1, 0, 0, 0, 1, 1, 1], [0, 1, 1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 0, 1, 1, 1, 1, 1, 1, 1], [0, 1, 0, 0, 1, 1, 1, 1, 1, 1]]


<h2>An improved algorithm for storing and tracing results</h2>

In [46]:
x = np.random.choice([0,1], size=(10,10))
initial_x = x.copy()

BETA = 1
num_iter = 1000000
results = []

for _ in range(num_iter):
    x_ij = np.random.choice(10, size=(2,))
    i, j = x_ij[0], x_ij[1]
    
    s_1, s_0 = 0, 0
    (s_1, s_0) = (s_1, s_0) if i == 0 else (s_1 + (x[i-1][j] == 1), s_0 + (x[i-1][j] == 0))
    (s_1, s_0) = (s_1, s_0) if i == 9 else (s_1 + (x[i+1][j] == 1), s_0 + (x[i+1][j] == 0))
    (s_1, s_0) = (s_1, s_0) if j == 0 else (s_1 + (x[i][j-1] == 1), s_0 + (x[i][j-1] == 0))
    (s_1, s_0) = (s_1, s_0) if j == 9 else (s_1 + (x[i][j+1] == 1), s_0 + (x[i][j+1] == 0))
    # print(s_1, s_0)
    
    e_s_1 = exp(BETA * s_1)
    e_s_0 = exp(BETA * s_0)
    
    p_1 = e_s_1 / (e_s_1 + e_s_0)
    # print(p_1)
    
    new_x_ij = np.random.choice([0,1], p=[1-p_1, p_1])
    # print(f"x[{i}][{j}]: {x[i][j]} => {new_x_ij}")

    x[i][j] = new_x_ij
    # results.append(x.copy())
    
    results.append((i, j, new_x_ij))

In [52]:
import pandas as pd
prob_table = np.zeros((2,2))

x_1_10, x_10_10 = initial_x[0][9], initial_x[9][9]

for r in results:
    if r[1] == 9:
        if r[0] == 0:
            x_1_10 = r[2]
        elif r[0] == 9:
            x_10_10 = r[2]
    prob_table[x_1_10][x_10_10] += 1

print(pd.DataFrame(prob_table / np.sum(prob_table)))

          0         1
0  0.231278  0.326089
1  0.241335  0.201298


<h2>Recap</h2>

In [13]:
import numpy as np
from math import exp
import pandas as pd

class Gibbs:
    def __init__(self, beta : float, num_iter : iter = 1000000):
        self.beta = beta
        self.num_iter = num_iter
        self.x = np.random.choice([0,1], size=(10,10))
        self.initial_x = self.x.copy()

    def run_sampling(self):
        self.results = []
        
        for _ in range(self.num_iter):
            x_ij = np.random.choice(10, size=(2,))
            i, j = x_ij[0], x_ij[1]
            
            s_1, s_0 = 0, 0
            (s_1, s_0) = (s_1, s_0) if i == 0 else (s_1 + (self.x[i-1][j] == 1), s_0 + (self.x[i-1][j] == 0))
            (s_1, s_0) = (s_1, s_0) if i == 9 else (s_1 + (self.x[i+1][j] == 1), s_0 + (self.x[i+1][j] == 0))
            (s_1, s_0) = (s_1, s_0) if j == 0 else (s_1 + (self.x[i][j-1] == 1), s_0 + (self.x[i][j-1] == 0))
            (s_1, s_0) = (s_1, s_0) if j == 9 else (s_1 + (self.x[i][j+1] == 1), s_0 + (self.x[i][j+1] == 0))
            # print(s_1, s_0)
            
            e_s_1 = exp(self.beta * s_1)
            e_s_0 = exp(self.beta * s_0)
            
            p_1 = e_s_1 / (e_s_1 + e_s_0)
            # print(p_1)
            
            new_x_ij = np.random.choice([0,1], p=[1-p_1, p_1])
            # print(f"x[{i}][{j}]: {x[i][j]} => {new_x_ij}")
        
            self.x[i][j] = new_x_ij
            # results.append(x.copy())
            
            self.results.append((i, j, new_x_ij))

    def compute_joint(self):
        prob_table = np.zeros((2,2))
        
        x_1_10, x_10_10 = self.initial_x[0][9], self.initial_x[9][9]
        
        for r in self.results:
            if r[1] == 9:
                if r[0] == 0:
                    x_1_10 = r[2]
                elif r[0] == 9:
                    x_10_10 = r[2]
            prob_table[x_1_10][x_10_10] += 1
        
        self.prob_table = pd.DataFrame(prob_table / np.sum(prob_table))

        print(self.prob_table)

    def run(self):
        self.run_sampling()
        self.compute_joint()

In [15]:
gibbs_4 = Gibbs(4)
gibbs_1 = Gibbs(1)
gibbs_001 = Gibbs(0.01)

In [17]:
gibbs_4.run()

          0         1
0  0.997739  0.001487
1  0.000756  0.000018


In [18]:
gibbs_1.run()

          0         1
0  0.354386  0.232140
1  0.205180  0.208294


In [19]:
gibbs_001.run()

          0         1
0  0.257205  0.250378
1  0.245429  0.246988
